<a href="https://colab.research.google.com/github/sandip-thakuri01/Data-Science-Projects/blob/main/Sampling%20and%20Statistics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df = pd.read_csv('/content/creditcard.csv')

In [ ]:
df.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0.0
1,0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0.0
2,1,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0.0
3,1,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0.0
4,2,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0.0

In [ ]:
df.describe()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
count,27819.000000,27818.000000,27818.000000,27818.000000,27818.000000,27818.000000,27818.000000,27818.000000,27818.000000,27818.000000,...,27818.000000,27818.000000,27818.000000,27818.000000,27818.000000,27818.000000,27818.000000,27818.000000,27818.000000,27818.000000
mean,20434.634315,-0.217255,0.149360,0.723559,0.221251,-0.199312,0.084607,-0.125687,0.028612,0.394412,...,-0.035045,-0.126646,-0.041207,0.010602,0.129963,0.023506,0.013398,0.004055,77.297298,0.003343
std,11866.057310,1.866645,1.545773,1.648474,1.425213,1.431480,1.325535,1.308413,1.314408,1.262314,...,0.803370,0.642121,0.544077,0.590914,0.436275,0.513862,0.393823,0.278450,219.651476,0.057724
min,0.000000,-30.552380,-40.978852,-31.103685,-5.172595,-42.147898,-23.496714,-26.548144,-41.484823,-7.175097,...,-20.262054,-8.593642,-26.751119,-2.836627,-7.495741,-1.338556,-8.567638,-9.617915,0.000000,0.000000
25%,9037.500000,-0.951060,-0.424408,0.271315,-0.690871,-0.788013,-0.658281,-0.595865,-0.162449,-0.420660,...,-0.246695,-0.547732,-0.174773,-0.326892,-0.132690,-0.336775,-0.063637,-0.008436,6.442500,0.000000
50%,24675.000000,-0.259642,0.163461,0.855090,0.202149,-0.230110,-0.174349,-0.068385,0.032587,0.305709,...,-0.093654,-0.100015,-0.049634,0.063056,0.169235,-0.054798,0.008119,0.020201,19.950000,0.000000
75%,31319.000000,1.166130,0.803933,1.483404,1.102574,0.316960,0.471794,0.445844,0.290104,1.152587,...,0.079173,0.281732,0.075486,0.398937,0.412015,0.305465,0.091483,0.076658,69.507500,0.000000
max,34712.000000,1.960497,16.713389,4.101716,13.143668,34.099309,22.529298,36.677268,20.007208,10.392889,...,22.614889,5.805795,13.876221,4.014444,5.525093,3.517346,11.135740,4.860769,7879.420000,1.000000

In [ ]:
data = df['Amount'].dropna().tolist()

In [ ]:
data.sort()
n = len(data)

Finding the quartiles

In [ ]:
# Median (Q2)
if n % 2 == 0:
    median = (data[n//2 - 1] + data[n//2]) / 2
else:
    median = data[n//2]

# Lower half and upper half
if n % 2 == 0:
    lower_half = data[:n//2]
    upper_half = data[n//2:]
else:
    lower_half = data[:n//2]
    upper_half = data[n//2+1:]

# Q1
m = len(lower_half)
if m % 2 == 0:
    Q1 = (lower_half[m//2 - 1] + lower_half[m//2]) / 2
else:
    Q1 = lower_half[m//2]

# Q3
m = len(upper_half)
if m % 2 == 0:
    Q3 = (upper_half[m//2 - 1] + upper_half[m//2]) / 2
else:
    Q3 = upper_half[m//2]

print("Q1:", Q1)
print("Median (Q2):", median)
print("Q3:", Q3)

Q1: 6.44
Median (Q2): 19.95
Q3: 69.51

Finding the Outliers using IQR method
formula = IQR = Q3-Q1
Lower Bound = Q1 -1.5(IQR)
Upper Bound = Q3 +1.5(IQR)

In [ ]:
IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

outliers = [x for x in data if x < lower_bound or x > upper_bound]

print("IQR:", IQR)
print("Lower Bound:", lower_bound)
print("Upper Bound:", upper_bound)
print("Number of Outliers:", len(outliers))

IQR: 63.07000000000001
Lower Bound: -88.16500000000002
Upper Bound: 164.115
Number of Outliers: 2865

Findng Means

In [ ]:
import math

In [ ]:
mean = sum(data) / n
print("Mean:", mean)

Mean: 77.29729779279603

Calculating the Standard Deviation:

In [ ]:
variance = sum((x - mean) ** 2 for x in data) / (n - 1)
sd = math.sqrt(variance)

print("Standard Deviation:", sd)

Standard Deviation: 219.65147554002942

In [ ]:
# Calculating the Skewness
skewness = (sum((x - mean) ** 3 for x in data) / n) / (sd ** 3)

print("Skewness:", skewness)

Skewness: 12.33633703888953

In [ ]:
#caluculating the Kurtosis
kurtosis = (sum((x - mean) ** 4 for x in data) / n) / (sd ** 4)

print("Kurtosis:", kurtosis)

Kurtosis: 271.94851269619625